/**
 * Copies compiled ABIs and the deployment record into web/ and matcher/ so the front-end and
 * the keeper never hand-maintain an ABI.
 *
 *   npm run sync-abi
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { ROOT } from "./constants.js";

const CONTRACTS = ["ZerkBook", "ZerkZone", "ZerkRWA"] as const;
const OUT_DIRS = [join(ROOT, "web", "lib", "generated"), join(ROOT, "matcher", "generated")];

function abiOf(name: string) {
  const path = join(ROOT, "artifacts", "contracts", `${name}.sol`, `${name}.json`);
  if (!existsSync(path)) throw new Error(`Missing artifact for ${name}. Run \`npm run build\`.`);
  return JSON.parse(readFileSync(path, "utf8")).abi;
}

function collectDeployments() {
  const dir = join(ROOT, "deployments");
  if (!existsSync(dir)) return {};
  const out: Record<string, unknown> = {};
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".json"))) {
    out[file.replace(".json", "")] = JSON.parse(readFileSync(join(dir, file), "utf8"));
  }
  return out;
}

const abis = Object.fromEntries(CONTRACTS.map((name) => [name, abiOf(name)]));
const deployments = collectDeployments();

const banner = "// Generated by `npm run sync-abi`. Do not edit.\n";

for (const dir of OUT_DIRS) {
  mkdirSync(dir, { recursive: true });

  writeFileSync(
    join(dir, "abis.ts"),
    `${banner}${CONTRACTS.map(
      (name) => `export const ${name}Abi = ${JSON.stringify(abis[name], null, 2)} as const;\n`
    ).join("\n")}`
  );

  writeFileSync(
    join(dir, "deployments.ts"),
    `${banner}export const deployments = ${JSON.stringify(deployments, null, 2)} as const;\n`
  );

  console.log(`  ↳ ${dir}`);
}

console.log(`Synced ${CONTRACTS.length} ABIs and ${Object.keys(deployments).length} deployment record(s).`);
